package testsprawnosci;

/*
 * test.java
 *
 * Created on 10 sierpień 2009, 19:56
 */



/**
 *
 * @author  Maciek
 */
public class test extends javax.swing.JFrame {
    
    /** Creates new form test */
    public test() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ocena testu sprawności fizycznej");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Ocena testu sprawności fizycznej");

        jLabel5.setText("Próba sprawnościowa");

        jLabel6.setText("Ilość punktów");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Bieg na 1000 m");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<=3,00", "3,02", "3,04", "3,06", "3,08", "3,10", "3,12", "3,14", "3,16", "3,18", "3,20", "3,21", "3,22", "3,23", "3,24", "3,25", "3,26", "3,27", "3,28", "3,29", "3,30", "3,31", "3,32", "3,33", "3,34", "3,35", "3,36", "3,37", "3,38", "3,39", "3,40", "3,42", "3,44", "3,46", "3,48", "3,50", "3,52", "3,54", "3,56", "3,58", "4,00", "4,02", "4,04", "4,06", "4,08", "4,10", "4,12", "4,14", "4,16", "4,18", "4,20", "4,22", "4,24", "4,26", "4,28", "4,30", "4,32", "4,34", "4,36", "4,38", "4,40", "4,42", "4,44", "4,46", "4,48", "4,50", "4,52", "4,54", "4,56", "4,58", "5,00", "5,10", "5,20", "5,30", "5,40", ">5,40" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel7.setText("75");

        jLabel3.setText("Bieg na 50 m");

        jLabel4.setText("Podciąganie na drążku");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<=6,4", "6,5", "6,6", "6,7", "6,8", "6,9", "7,0", "7,1", "7,2", "7,3", "7,4", "7,5", "7,6", "7,7", "7,8", "7,9", "8,0", "8,1", "8,2", "8,3", "8,4", "8,5", "8,6", "8,7", "8,8", ">8,8" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">=24", "23", "22", "21", "20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1", "0" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jLabel8.setText("75");

        jLabel9.setText("75");

        jLabel12.setText("75");

        jLabel10.setText("Średnia ilość punktów");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jLabel14.setText("Komenda Powiatowa Państwowej Straży Pożarnej w Wałczu");

        jLabel15.setText("http://www.strazwalcz.pl");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(128, 128, 128)
                .addComponent(jLabel6)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(1, 1, 1)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
if(evt.getItem()=="<=3,00") {jLabel7.setText("75");}
if(evt.getItem()=="3,02") {jLabel7.setText("74");}
if(evt.getItem()=="3,04") {jLabel7.setText("73");}
if(evt.getItem()=="3,06") {jLabel7.setText("72");}
if(evt.getItem()=="3,08") {jLabel7.setText("71");}
if(evt.getItem()=="3,10") {jLabel7.setText("70");}
if(evt.getItem()=="3,12") {jLabel7.setText("69");}
if(evt.getItem()=="3,14") {jLabel7.setText("68");}
if(evt.getItem()=="3,16") {jLabel7.setText("67");}
if(evt.getItem()=="3,18") {jLabel7.setText("66");}
if(evt.getItem()=="3,20") {jLabel7.setText("65");}
if(evt.getItem()=="3,21") {jLabel7.setText("64");}
if(evt.getItem()=="3,22") {jLabel7.setText("63");}
if(evt.getItem()=="3,23") {jLabel7.setText("62");}
if(evt.getItem()=="3,24") {jLabel7.setText("61");}
if(evt.getItem()=="3,25") {jLabel7.setText("60");}
if(evt.getItem()=="3,26") {jLabel7.setText("59");}
if(evt.getItem()=="3,27") {jLabel7.setText("58");}
if(evt.getItem()=="3,28") {jLabel7.setText("57");}
if(evt.getItem()=="3,29") {jLabel7.setText("56");}
if(evt.getItem()=="3,30") {jLabel7.setText("55");}
if(evt.getItem()=="3,31") {jLabel7.setText("54");}
if(evt.getItem()=="3,32") {jLabel7.setText("53");}
if(evt.getItem()=="3,33") {jLabel7.setText("52");}
if(evt.getItem()=="3,34") {jLabel7.setText("51");}
if(evt.getItem()=="3,35") {jLabel7.setText("50");}
if(evt.getItem()=="3,36") {jLabel7.setText("49");}
if(evt.getItem()=="3,37") {jLabel7.setText("48");}
if(evt.getItem()=="3,38") {jLabel7.setText("47");}
if(evt.getItem()=="3,39") {jLabel7.setText("46");}
if(evt.getItem()=="3,40") {jLabel7.setText("45");}
if(evt.getItem()=="3,42") {jLabel7.setText("44");}
if(evt.getItem()=="3,44") {jLabel7.setText("43");}
if(evt.getItem()=="3,46") {jLabel7.setText("42");}
if(evt.getItem()=="3,48") {jLabel7.setText("41");}
if(evt.getItem()=="3,50") {jLabel7.setText("40");}
if(evt.getItem()=="3,52") {jLabel7.setText("39");}
if(evt.getItem()=="3,54") {jLabel7.setText("38");}
if(evt.getItem()=="3,56") {jLabel7.setText("37");}
if(evt.getItem()=="3,58") {jLabel7.setText("36");}
if(evt.getItem()=="4,00") {jLabel7.setText("35");}
if(evt.getItem()=="4,02") {jLabel7.setText("34");}
if(evt.getItem()=="4,04") {jLabel7.setText("33");}
if(evt.getItem()=="4,06") {jLabel7.setText("32");}
if(evt.getItem()=="4,08") {jLabel7.setText("31");}
if(evt.getItem()=="4,10") {jLabel7.setText("30");}
if(evt.getItem()=="4,12") {jLabel7.setText("29");}
if(evt.getItem()=="4,14") {jLabel7.setText("28");}
if(evt.getItem()=="4,16") {jLabel7.setText("27");}
if(evt.getItem()=="4,18") {jLabel7.setText("26");}
if(evt.getItem()=="4,20") {jLabel7.setText("25");}
if(evt.getItem()=="4,22") {jLabel7.setText("24");}
if(evt.getItem()=="4,24") {jLabel7.setText("23");}
if(evt.getItem()=="4,26") {jLabel7.setText("22");}
if(evt.getItem()=="4,28") {jLabel7.setText("21");}
if(evt.getItem()=="4,30") {jLabel7.setText("20");}
if(evt.getItem()=="4,32") {jLabel7.setText("19");}
if(evt.getItem()=="4,34") {jLabel7.setText("18");}
if(evt.getItem()=="4,36") {jLabel7.setText("17");}
if(evt.getItem()=="4,38") {jLabel7.setText("16");}
if(evt.getItem()=="4,40") {jLabel7.setText("15");}
if(evt.getItem()=="4,42") {jLabel7.setText("14");}
if(evt.getItem()=="4,44") {jLabel7.setText("13");}
if(evt.getItem()=="4,46") {jLabel7.setText("12");}
if(evt.getItem()=="4,48") {jLabel7.setText("11");}
if(evt.getItem()=="4,50") {jLabel7.setText("10");}
if(evt.getItem()=="4,52") {jLabel7.setText("9");}
if(evt.getItem()=="4,54") {jLabel7.setText("8");}
if(evt.getItem()=="4,56") {jLabel7.setText("7");}
if(evt.getItem()=="4,58") {jLabel7.setText("6");}
if(evt.getItem()=="5,00") {jLabel7.setText("5");}
if(evt.getItem()=="5,10") {jLabel7.setText("4");}
if(evt.getItem()=="5,20") {jLabel7.setText("3,5");}
if(evt.getItem()=="5,30") {jLabel7.setText("3");}
if(evt.getItem()=="5,40") {jLabel7.setText("2");}
if(evt.getItem()==">5,40") {jLabel7.setText("0");}
oblicz();
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ItemStateChanged

private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
if(evt.getItem()=="<=6,4") {jLabel8.setText("75");}
if(evt.getItem()=="6,5") {jLabel8.setText("73");}
if(evt.getItem()=="6,6") {jLabel8.setText("71");}
if(evt.getItem()=="6,7") {jLabel8.setText("68");}
if(evt.getItem()=="6,8") {jLabel8.setText("65");}
if(evt.getItem()=="6,9") {jLabel8.setText("60");}
if(evt.getItem()=="7,0") {jLabel8.setText("55");}
if(evt.getItem()=="7,1") {jLabel8.setText("50");}
if(evt.getItem()=="7,2") {jLabel8.setText("45");}
if(evt.getItem()=="7,3") {jLabel8.setText("42");}
if(evt.getItem()=="7,4") {jLabel8.setText("38");}
if(evt.getItem()=="7,5") {jLabel8.setText("35");}
if(evt.getItem()=="7,6") {jLabel8.setText("32");}
if(evt.getItem()=="7,7") {jLabel8.setText("28");}
if(evt.getItem()=="7,8") {jLabel8.setText("25");}
if(evt.getItem()=="7,9") {jLabel8.setText("22");}
if(evt.getItem()=="8,0") {jLabel8.setText("18");}
if(evt.getItem()=="8,1") {jLabel8.setText("15");}
if(evt.getItem()=="8,2") {jLabel8.setText("12");}
if(evt.getItem()=="8,3") {jLabel8.setText("8");}
if(evt.getItem()=="8,4") {jLabel8.setText("5");}
if(evt.getItem()=="8,5") {jLabel8.setText("4");}
if(evt.getItem()=="8,6") {jLabel8.setText("3,5");}
if(evt.getItem()=="8,7") {jLabel8.setText("3");}
if(evt.getItem()=="8,8") {jLabel8.setText("2");}
if(evt.getItem()==">8,8") {jLabel8.setText("0");}
oblicz();
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ItemStateChanged

private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
if(evt.getItem()==">=24") {jLabel9.setText("75");}
if(evt.getItem()=="23") {jLabel9.setText("74");}
if(evt.getItem()=="22") {jLabel9.setText("73");}
if(evt.getItem()=="21") {jLabel9.setText("72");}
if(evt.getItem()=="20") {jLabel9.setText("71");}
if(evt.getItem()=="19") {jLabel9.setText("70");}
if(evt.getItem()=="18") {jLabel9.setText("69");}
if(evt.getItem()=="17") {jLabel9.setText("68");}
if(evt.getItem()=="16") {jLabel9.setText("67");}
if(evt.getItem()=="15") {jLabel9.setText("66");}
if(evt.getItem()=="14") {jLabel9.setText("65");}
if(evt.getItem()=="13") {jLabel9.setText("62");}
if(evt.getItem()=="12") {jLabel9.setText("59");}
if(evt.getItem()=="11") {jLabel9.setText("55");}
if(evt.getItem()=="10") {jLabel9.setText("50");}
if(evt.getItem()=="9") {jLabel9.setText("45");}
if(evt.getItem()=="8") {jLabel9.setText("40");}
if(evt.getItem()=="7") {jLabel9.setText("35");}
if(evt.getItem()=="6") {jLabel9.setText("25");}
if(evt.getItem()=="5") {jLabel9.setText("20");}
if(evt.getItem()=="4") {jLabel9.setText("15");}
if(evt.getItem()=="3") {jLabel9.setText("10");}
if(evt.getItem()=="2") {jLabel9.setText("5");}
if(evt.getItem()=="1") {jLabel9.setText("1");}
if(evt.getItem()=="0") {jLabel9.setText("0");}
oblicz();
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox3ItemStateChanged
private void oblicz(){
    int a,b,c,e;

a = Integer.valueOf(jLabel7.getText());
b = Integer.valueOf(jLabel8.getText());
c = Integer.valueOf(jLabel9.getText());
//float d = (a+b+c)/3;
e = Math.round((a+b+c)/3);

jLabel12.setText(Integer.toString(e));
//if (e<=45) { jLabel13.setText("niedostateczna");};
//if (e>45&&e<=50) { jLabel13.setText("słaba");};
//if (e>50&&e<=55) { jLabel13.setText("dostateczna");};
//if (e>55&&e<=60) { jLabel13.setText("dobra");};
//if (e>60&&e<=65) { jLabel13.setText("bardzo dobra");};
//if (e>65) { jLabel13.setText("wybitna");};
}
private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jLabel15MouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
             
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
